name: wear_text_input
description: A new Flutter plugin project.
version: 1.0.0
homepage: colorhub.online

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: online.colorhub.wear_text_input
        pluginClass: WearTextInputPlugin